[general]
static=yes
writeprotect=no

[from-internal]
exten => 100,1,Dial(PJSIP/100,60)
 same => n,Hangup()

exten => 200,1,Dial(PJSIP/200,60)
 same => n,Hangup()

exten => 600,1,Answer()
 same => n,Echo()
 same => n,Hangup()
